site_name: ZephyrCab Docs
pages:
- Welcome: index.md
- Getting Started:
  - Quick Start: quick-start.md
  - Basic Configuration: userguide/configuring-settings-json.md
  - Adding your Locomotives: userguide/configuring-bundles-json.md
- Supported Models: reference/supported.md
- How It Works: userguide/how-it-works.md
- Developer Reference: dev-reference/index.md

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

theme_dir: 'mkdocs-material/material'
copyright: ZephyrCab is free software, released with no license.
repo_name: 'k4kfh/ZephyrCab'
repo_url: 'https://github.com/k4kfh/ZephyrCab'
